name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache deps
        uses: actions/cache@v2
        env:
          cache-name: cache-deps
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run tests
        run: cd kpiexport && cargo test
      - name: Build
        run: cd kpiexport && cargo build --release
      - name: Release binary
        uses: actions/upload-artifact@v2
        with:
          name: release-binary
          path: kpiexport/target/release/kpiexport
  build_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: release-binary
          path: kpiexport/target/release/kpiexport
      - name: Publish docker image to Github Packages
        uses: docker/build-push-action@v2
        with:
          tags: docker.pkg.github.com/nikitavbv/kpiexport/kpiexport
          context: kpiexport
