name: NGINX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - name: build frontend
        run: cd kpiexport_frontend && yarn install && yarn build && cd ..
      - name: Build
        run: docker build -f kpiexport_frontend/nginx/Dockerfile kpiexport_frontend
      - name: Publish docker image to Github Packages
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/nikitavbv/kpiexport3/frontend
          registry: docker.pkg.github.com
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}