name: NGINX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - name: build frontend
        run: cd kpiexport_frontend && yarn install && yarn build && cd ..
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
      - name: Publish docker image to eu.gcr.io
        uses: docker/build-push-action@v2
        with:
          tags: "eu.gcr.io/nikitavbv/nikitavbv/kpiexport_frontend:0.1.${{ github.run_number }}"
          push: true
          context: kpiexport_frontend
          file: kpiexport_frontend/nginx/Dockerfile
      - run: echo "Pushed eu.gcr.io/nikitavbv/nikitavbv/kpiexport:0.1.${{ github.run_number }}"