name: NGINX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -f kpiexport_frontend/nginx/Dockerfile kpiexport_frontend
